apiVersion: v2
name: fdr-chart
description: Flussi di rendicontazione
type: application
version: 2.1.2
appVersion: 2.1.2
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: fdrnodo
