apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.99.0
appVersion: 0.3.7
dependencies:
  - name: microservice-chart
    version: 8.0.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
