apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.98.0
appVersion: 0.3.6
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
