apiVersion: v2
name: wisp-soap-converter-chart
description: Wisp Soap Conveter
type: application
version: 2.39.0
appVersion: 0.2.6-71-PAGOPA-1899-redirect-url
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: wispsoapconverter
